#!/usr/bin/env node
/**
 * csmp.gs ... get/send
 *
 * gs fromurl tourl
 */
(function() {
  var getreq,
      http    = require('http'),
      prog    = require('commander');

  prog.version("0.0.1")
  .option("-s, --server <server>", "server name to get data from (default is localhost)")
  .option("-o, --path <path>", "path to get data from (dbname/id)")
  .option("-p, --port <port>", "from port (default is  5984)", parseInt)
  .parse(process.argv);

  var  path = prog.path;

  if(path){
    var postops = {
      hostname: prog.server ? prog.server : "localhost",
      port: prog.port     ? prog.port     : 8001,
      path: "/" + path,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' }
    };

    process.stdin.setEncoding('utf8');
    process.stdin.on('readable', function(chunk) {
      chunk = process.stdin.read();
      if (chunk !== null) {
        postreq.write(chunk);
      }
      postreq.end();
    });
    process.stdin.on('end', function() {
      process.stdout.write("end stdin\n");
    });

    var tocb = function(res) {
      var str = ''
      res.on('data', function (chunk) {
        str += chunk;
      });
      res.on('end', function () {
        process.stdout.write("end http\n");
      });
    }

    var postreq = http.request(postops, tocb);
    postreq.on('error', function(e) {
      process.stderr.write("http get error " + e.message);
    });
  }
})();