#!/usr/bin/env node
/**
 *  get data from stdin write to ssmp
 */
(function() {
  var prog       = require('commander'),
      utils      = require('./lib/utils');

  prog.version("0.0.1")
  .option("-s, --server <server>", "server name to get data from (default is localhost)")
  .option("-o, --path <path>", "path to get data from (dbname/id)")
  .option("-p, --port <port>", "from port (default is  5984)", parseInt)
  .parse(process.argv);

  if(prog.path){
    var con = {
      hostname: prog.server ? prog.server : "localhost",
      port:     prog.port   ? prog.port   : 8001,
      path: "/" + prog.path,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      }
    };

    utils.stdin2http(
      utils.httpreq(con)
    );
  }
})();